import { ArrowLeft, AlertTriangle, CheckCircle2, FileWarning } from 'lucide-react';
import { unstable_setRequestLocale } from 'next-intl/server';
import { Link } from '@/i18n/navigation';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { buildHreflangAlternates } from '@/lib/hreflang';

interface PageProps {
  params: { locale: string };
}

export async function generateMetadata({ params }: PageProps) {
  unstable_setRequestLocale(params.locale);
  const alternates = await buildHreflangAlternates('/sample-report');
  return {
    title: 'Sample audit report — LexyFlow',
    alternates: { canonical: `/${params.locale}/sample-report`, languages: alternates }
  };
}

/**
 * A static, hand-curated example of what LexyFlow produces. Written in
 * English (the pivot language) to demonstrate the depth of analysis;
 * production reports localize to the user's language via Pass 2.
 */
export default async function SampleReportPage({ params: { locale } }: PageProps) {
  unstable_setRequestLocale(locale);

  const findings = [
    {
      severity: 'critical' as const,
      framework: 'GDPR Art. 13(2)(a)',
      title: 'Retention period not specified for marketing data',
      body: 'The privacy policy commits to keeping prospect data "as long as necessary" without an objective duration or criterion. Article 13(2)(a) requires the controller to inform the data subject of the period for which the personal data will be stored, or, if not possible, the criteria used to determine that period.',
      recommendation: 'Replace the wording with a concrete duration (e.g. "36 months from last interaction") or a criterion ("until you unsubscribe"). Document the same in the Article 30 register.'
    },
    {
      severity: 'high' as const,
      framework: 'EU AI Act Art. 52(1)',
      title: 'No transparency notice for AI-generated content',
      body: 'The product page mentions "AI-assisted recommendations" without disclosing that the output is machine-generated. From August 2026, deployers of generative AI systems must inform users that they are interacting with AI.',
      recommendation: 'Add a discreet but visible "AI-generated content" label on every AI-produced surface (recommendations, summaries, drafts).'
    },
    {
      severity: 'medium' as const,
      framework: 'LGPD Art. 9',
      title: 'Consent legal basis is bundled with terms acceptance',
      body: 'The Brazilian onboarding flow asks the user to accept the Terms of Service and consent to data processing in a single checkbox. LGPD Art. 9 requires consent to be free, informed and unambiguous, which precludes bundling.',
      recommendation: 'Split the checkbox into two: one for ToS, one for explicit consent on data processing. Log the timestamp and IP for each independently.'
    }
  ];

  return (
    <div className="mx-auto max-w-3xl py-16">
      <Button asChild variant="ghost" size="sm" className="-ms-3">
        <Link href="/">
          <ArrowLeft className="me-2 h-4 w-4 rtl:-scale-x-100" />
          Back
        </Link>
      </Button>

      <header className="mt-6 grid gap-3">
        <Badge variant="outline" className="w-fit">Sample report</Badge>
        <h1 className="text-balance text-3xl font-semibold tracking-tight md:text-4xl">
          Privacy policy audit — Acme Inc.
        </h1>
        <p className="text-pretty text-muted-foreground">
          Generated by LexyFlow in 47 seconds. 3 frameworks cross-referenced.
          Risk score: <span className="font-semibold text-foreground">68 / 100</span>.
        </p>
      </header>

      <section className="mt-10 grid gap-4">
        <h2 className="text-sm font-semibold uppercase tracking-wider text-muted-foreground">
          Findings
        </h2>
        {findings.map((f, i) => (
          <Card key={i}>
            <CardHeader>
              <div className="flex items-start gap-3">
                <SeverityIcon severity={f.severity} />
                <div className="flex-1 space-y-1">
                  <div className="flex items-center gap-2">
                    <Badge variant={f.severity === 'critical' ? 'destructive' : 'secondary'}>
                      {f.severity}
                    </Badge>
                    <span className="font-mono text-xs text-muted-foreground">{f.framework}</span>
                  </div>
                  <CardTitle className="text-base leading-tight">{f.title}</CardTitle>
                </div>
              </div>
            </CardHeader>
            <CardContent className="space-y-3 text-sm">
              <CardDescription className="text-pretty">{f.body}</CardDescription>
              <div className="rounded-md border bg-muted/50 p-3">
                <div className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                  Recommendation
                </div>
                <p className="mt-1 text-pretty">{f.recommendation}</p>
              </div>
            </CardContent>
          </Card>
        ))}
      </section>

      <section className="mt-12 rounded-lg border bg-muted/40 p-6 text-center">
        <p className="text-pretty">
          Real reports include source-document evidence, a remediation
          timeline, and a downloadable PDF — in any of 100+ languages.
        </p>
        <Button asChild size="lg" className="mt-4">
          <Link href="/audit">Run an audit on your own document</Link>
        </Button>
      </section>
    </div>
  );
}

function SeverityIcon({ severity }: { severity: 'critical' | 'high' | 'medium' }) {
  if (severity === 'critical') return <AlertTriangle className="mt-1 h-5 w-5 text-destructive" />;
  if (severity === 'high')     return <FileWarning className="mt-1 h-5 w-5 text-orange-500" />;
  return <CheckCircle2 className="mt-1 h-5 w-5 text-muted-foreground" />;
}
